# 1. Wajib: Project Key harus sama dengan yang ada di SonarQube Web
sonar.projectKey=evershop-maintainability-test

# 2. Wajib: Lokasi kode sumber automation Anda
sonar.sources=cypress/e2e

# 3. Opsional tapi disarankan: Bahasa
sonar.language=java

# Abaikan file yang tidak perlu dianalisis (opsional)
sonar.exclusions=**/*.xml, **/*.json

sonar.host.url=http://localhost:9000