# 1. Wajib: Project Key
sonar.projectKey=evershop-maintainability-test
sonar.projectName=evershop-maintainability-test

# 2. Wajib: Lokasi kode sumber yang Anda inginkan
sonar.sources=packages/evershop/src/modules

# 3. Wajib: Bahasa (js/ts)
sonar.language=js 

# 4. Eksklusi (Untuk mengabaikan file yang mungkin tidak perlu, atau library)
sonar.exclusions=packages/evershop/src/modules/**/*.xml, packages/evershop/src/modules/**/*.json

# --- SETTING PENTING UNTUK MENGATASI PARSE ERROR ---
# Ini memberitahu scanner untuk menggunakan mode yang lebih permisif/modern 
# agar dapat melewati fitur-fitur seperti Optional Chaining.
sonar.javascript.ecmascript=2020